package com.danesh.bp.field48


object BpField48Tags {
    const val POS_BRAND = "01"
    const val COMMUNICATION_TYPE = "02"
    const val POS_MODEL = "03"
    const val LAST_SUCCESS_STAN = "04"
    const val LAST_SUCCESS_RRN = "05"
    const val BANK_NAME = "06"
    const val TAX_ID = "07"
    const val FORCE_KEY_RELOAD = "08"
    const val MERCHANT_NAME_FA = "09"
    const val MERCHANT_PHONE = "0A"
    const val MERCHANT_ADDRESS = "0B"
    const val MERCHANT_NAME_EN = "0C"
    const val MERCHANT_POSTAL_CODE = "0D"
    const val CHARGE_SERIAL = "0E"
    const val CHARGE_PIN = "0F"
    const val VOUCHER_AMOUNT = "10"
    const val BILL_ID = "11"
    const val PAYMENT_ID = "12"
    const val SWITCH_IP = "13"
    const val TERMINAL_IP = "14"
    const val SWITCH_PORT = "15"
    const val SWITCH_DATE_TIME = "16"
    const val SUPPORT_PHONE = "17"
    const val MOBILE_OPERATOR = "18"
    const val MOBILE_NUMBER = "19"
    const val SERVICE = "1A"
    const val SERVICE_CODE = "1B"
    const val SERVICE_HELP_TEXT = "1C"
    const val TERMINAL_SHAPARAK_ID = "1D"
    const val KEY_INDEX = "1E"
    const val LAST_KEY_INDEX = "1F"
    const val CREDIT_BALANCE = "20"
    const val CREDIT_USED_OR_REQUIRED = "21"
    const val CANCEL_REASON = "22"
    const val SUPPORT_TITLES_AMOUNTS = "23"
    const val REFUND_AMOUNT = SUPPORT_TITLES_AMOUNTS
    const val SUPPORT_MENU_ITEMS = "24"
    const val VAT_PERCENT = "25"

}
